---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Messages
  - Safari
  - Music
  - Notes
  - Reminders
  - FaceTime
  - Photos
  - Maps
  - Contacts
  - Calendar
  - News
  - 'System Settings'
  - Podcasts
  - 'App Store'
dockitems_persist:
  - name: "Mail"
    path: "/Applications/Mail.app/"
    pos: 2
  - name: "PhpStorm"
    path: "/Users/dustinwalker/Applications/JetBrains Toolbox/PhpStorm.app/"
    pos: 3
  - name: "Tower"
    path: "/Applications/Tower.app/"
    pos: 4
  - name: "Warp"
    path: "/Applications/Warp.app/"
    pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/dustinwalker/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - composer
  - git
  - github/gh/gh
  - gpg
  - iperf
  - libevent
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - openssl
  - wget
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - slack
  - sublime-text
  - transmit
  - orion
  - warp
  - iterm2
  - microsoft-teams
  - tower
  - alfred
  - fig
  - jetbrains-toolbox
  - zoom
  - kaleidoscope
  - splashtop-personal
  - fantastical
  - visual-studio-code
  - setapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
